pre_development:
  sessions:
    default:
      database: fresh_writing_development
      hosts:
        - localhost:27017
pre_production:
  sessions:
    default:
      database: freshwriting_pre_production
      hosts:
        - dbpprd.library.nd.edu:27017
production:
  sessions:
    default:
      database: freshwriting_production
      hosts:
        - dbprod.library.nd.edu:27017
