development:
  clients:
    default:
      database: fresh_writing_development
      hosts:
        - localhost:27017
pre_production:
  clients:
    default:
      database: freshwriting_pprd
      hosts:
        - dbpprd.library.nd.edu:27017
production:
  clients:
    default:
      database: freshwriting_prod
      hosts:
        - dbprod.library.nd.edu:27017
staging:
  clients:
    default:
      database: fresh_writing_staging
      hosts:
        - localhost:27017
